-- Enable Extensions
CREATE EXTENSION IF NOT EXISTS fuzzystrmatch;
CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE EXTENSION IF NOT EXISTS vector;

-- Enums
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'providers') THEN
    CREATE TYPE providers AS ENUM ('Email', 'Microsoft', 'Google');
  END IF;
END
$$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'status') THEN
    CREATE TYPE status AS ENUM ('ACTIVE', 'INACTIVE');
  END IF;
END
$$;

CREATE TABLE app_user (
  id SERIAL PRIMARY KEY,
  first_name TEXT,
  last_name TEXT,
  password TEXT NOT NULL,
  email TEXT NOT NULL UNIQUE,
  is_active BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by INTEGER REFERENCES app_user(id) ON DELETE SET NULL ON UPDATE CASCADE,
  provider providers[] DEFAULT '{}'
);

CREATE TABLE role (
  id SERIAL PRIMARY KEY,
  role_name TEXT NOT NULL UNIQUE,
  description TEXT,
  created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by INTEGER REFERENCES app_user(id) ON DELETE SET NULL ON UPDATE CASCADE
);

-- Add role_id after both exist
ALTER TABLE app_user
ADD COLUMN role_id INTEGER REFERENCES role(id) ON DELETE SET NULL ON UPDATE CASCADE;

-- Project
CREATE TABLE project (
  id SERIAL PRIMARY KEY,
  title TEXT NOT NULL,
  service_type TEXT UNIQUE,
  status status DEFAULT 'ACTIVE',
  created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by INTEGER REFERENCES app_user(id) ON DELETE SET NULL ON UPDATE CASCADE,
  updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Upload History
CREATE TABLE upload_history (
  id SERIAL PRIMARY KEY,
  file_name TEXT NOT NULL,
  uploaded_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  uploaded_by INTEGER REFERENCES app_user(id) ON DELETE SET NULL ON UPDATE CASCADE,
  status TEXT NOT NULL,
  project_id INTEGER REFERENCES project(id) ON DELETE SET NULL ON UPDATE CASCADE
);

-- Question
CREATE TABLE question (
  id SERIAL PRIMARY KEY,
  topic TEXT,
  stage TEXT,
  source TEXT,
  question_text TEXT NOT NULL,
  answer_text TEXT,
  embedding vector(1024) NOT NULL,
  created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by INTEGER REFERENCES app_user(id) ON DELETE SET NULL ON UPDATE CASCADE,
  updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by INTEGER REFERENCES app_user(id) ON DELETE SET NULL ON UPDATE CASCADE,
  upload_id INTEGER REFERENCES upload_history(id) ON DELETE SET NULL ON UPDATE CASCADE,
  project_id INTEGER REFERENCES project(id) ON DELETE SET NULL ON UPDATE CASCADE
);

-- Session
CREATE TABLE session (
  id SERIAL PRIMARY KEY,
  title TEXT NOT NULL,
  user_id INTEGER REFERENCES app_user(id) ON DELETE SET NULL ON UPDATE CASCADE,
  created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Chat
CREATE TABLE chat (
  id SERIAL PRIMARY KEY,
  topic TEXT,
  stage TEXT,
  source TEXT,
  question_text TEXT NOT NULL,
  answer_text TEXT,
  project_id INTEGER REFERENCES project(id) ON DELETE SET NULL ON UPDATE CASCADE,
  user_id INTEGER REFERENCES app_user(id) ON DELETE SET NULL ON UPDATE CASCADE,
  session_id INTEGER REFERENCES session(id) ON DELETE SET NULL ON UPDATE CASCADE,
  created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  embedding vector(1024)
);

-- API Keys
CREATE TABLE api_key (
  id SERIAL PRIMARY KEY,
  key TEXT NOT NULL UNIQUE,
  description TEXT,
  created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by INTEGER REFERENCES app_user(id) ON DELETE SET NULL ON UPDATE CASCADE,
  updated_by INTEGER REFERENCES app_user(id) ON DELETE SET NULL ON UPDATE CASCADE
);