CREATE TABLE password_reset (
  id SERIAL PRIMARY KEY,
  user_id INTEGER REFERENCES app_user(id) ON DELETE SET NULL ON UPDATE CASCADE,
  reset_code TEXT NOT NULL,
  expire_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
